import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { of } from 'rxjs';
import { Car } from './app.const';


@Injectable()
export class CarService {

    constructor(private http: HttpClient) {}

    getCarsSmall() {
        return of([{
            "vin": "acfca5bf",
            "brand": "Blogpad",
            "year": 1992,
            "color": "Yellow"
        }, {
            "vin": "5e3bb412",
            "brand": "Twinte",
            "year": 2002,
            "color": "Yellow"
        }, {
            "vin": "b659a73a",
            "brand": "Brainlounge",
            "year": 1992,
            "color": "Khaki"
        }, {
            "vin": "123b9815",
            "brand": "Kanoodle",
            "year": 2000,
            "color": "Yellow"
        }, {
            "vin": "e76bc96f",
            "brand": "Meejo",
            "year": 2012,
            "color": "Fuscia"
        }, {
            "vin": "f09d76ff",
            "brand": "Jazzy",
            "year": 2009,
            "color": "Turquoise"
        }, {
            "vin": "b7d69468",
            "brand": "Youfeed",
            "year": 2011,
            "color": "Turquoise"
        }, {
            "vin": "fdf3b734",
            "brand": "Dazzlesphere",
            "year": 1997,
            "color": "Violet"
        }, {
            "vin": "3c339b5b",
            "brand": "Meezzy",
            "year": 2012,
            "color": "Purple"
        }, {
            "vin": "9632d80a",
            "brand": "Zoonder",
            "year": 1995,
            "color": "Maroon"
        }, {
            "vin": "30168ed2",
            "brand": "Vimbo",
            "year": 2012,
            "color": "Khaki"
        }, {
            "vin": "42e69167",
            "brand": "Snaptags",
            "year": 2011,
            "color": "Orange"
        }, {
            "vin": "e8c77fc6",
            "brand": "Skyvu",
            "year": 2001,
            "color": "Orange"
        }, {
            "vin": "e7296375",
            "brand": "Youspan",
            "year": 2005,
            "color": "Goldenrod"
        }, {
            "vin": "0390aadd",
            "brand": "Fivechat",
            "year": 1997,
            "color": "Aquamarine"
        }, {
            "vin": "755da434",
            "brand": "Yambee",
            "year": 2006,
            "color": "Khaki"
        }, {
            "vin": "4a544a79",
            "brand": "Tavu",
            "year": 1970,
            "color": "Indigo"
        }, {
            "vin": "ff2bb1f6",
            "brand": "Ntags",
            "year": 2013,
            "color": "Yellow"
        }, {
            "vin": "93cb9ab0",
            "brand": "Zoomdog",
            "year": 1999,
            "color": "Red"
        }, {
            "vin": "efdae20c",
            "brand": "Skipstorm",
            "year": 1995,
            "color": "Turquoise"
        }, {
            "vin": "2f873582",
            "brand": "Photolist",
            "year": 2004,
            "color": "Crimson"
        }, {
            "vin": "08f5506c",
            "brand": "Mydeo",
            "year": 1996,
            "color": "Aquamarine"
        }, {
            "vin": "8590223c",
            "brand": "Riffpedia",
            "year": 2005,
            "color": "Pink"
        }, {
            "vin": "7540d4a9",
            "brand": "Linklinks",
            "year": 2010,
            "color": "Crimson"
        }, {
            "vin": "a8667fd3",
            "brand": "Gabcube",
            "year": 2006,
            "color": "Teal"
        }, {
            "vin": "48d907fe",
            "brand": "Mynte",
            "year": 1993,
            "color": "Yellow"
        }, {
            "vin": "25cf1908",
            "brand": "Realmix",
            "year": 2000,
            "color": "Khaki"
        }, {
            "vin": "89f8e91a",
            "brand": "Avaveo",
            "year": 1989,
            "color": "Orange"
        }, {
            "vin": "22ae3dec",
            "brand": "Divape",
            "year": 2003,
            "color": "Crimson"
        }, {
            "vin": "347b3853",
            "brand": "Fiveclub",
            "year": 1997,
            "color": "Fuscia"
        }, {
            "vin": "f393bdfc",
            "brand": "Skipfire",
            "year": 1991,
            "color": "Aquamarine"
        }, {
            "vin": "28efa618",
            "brand": "Brainverse",
            "year": 1976,
            "color": "Maroon"
        }, {
            "vin": "095bfc58",
            "brand": "Kwideo",
            "year": 2005,
            "color": "Purple"
        }, {
            "vin": "14a69fdb",
            "brand": "Mycat",
            "year": 2007,
            "color": "Fuscia"
        }, {
            "vin": "1746db2d",
            "brand": "Youspan",
            "year": 1988,
            "color": "Green"
        }, {
            "vin": "21b4fa4c",
            "brand": "Meeveo",
            "year": 1992,
            "color": "Red"
        }, {
            "vin": "507af49b",
            "brand": "Riffwire",
            "year": 2002,
            "color": "Indigo"
        }, {
            "vin": "541f0fef",
            "brand": "Livefish",
            "year": 2012,
            "color": "Turquoise"
        }, {
            "vin": "ab2bc584",
            "brand": "Topicware",
            "year": 2011,
            "color": "Yellow"
        }, {
            "vin": "4a001006",
            "brand": "Tazz",
            "year": 1992,
            "color": "Violet"
        }, {
            "vin": "dcd3201c",
            "brand": "Skyndu",
            "year": 2006,
            "color": "Purple"
        }, {
            "vin": "de482712",
            "brand": "Bluezoom",
            "year": 2012,
            "color": "Red"
        }, {
            "vin": "bae0bed6",
            "brand": "Livefish",
            "year": 1967,
            "color": "Maroon"
        }, {
            "vin": "9e8b05d4",
            "brand": "Wordware",
            "year": 1998,
            "color": "Green"
        }, {
            "vin": "bf4ce825",
            "brand": "Twitterlist",
            "year": 1998,
            "color": "Crimson"
        }, {
            "vin": "ec769fa0",
            "brand": "Realfire",
            "year": 2006,
            "color": "Green"
        }, {
            "vin": "0b107e6d",
            "brand": "Zoonoodle",
            "year": 2004,
            "color": "Violet"
        }, {
            "vin": "c186ccb0",
            "brand": "Voonyx",
            "year": 1993,
            "color": "Purple"
        }, {
            "vin": "0cffa015",
            "brand": "Fanoodle",
            "year": 2013,
            "color": "Crimson"
        }, {
            "vin": "2e2b018a",
            "brand": "Wordify",
            "year": 2004,
            "color": "Violet"
        }
    ]
        );
    }
}
